"""Read-only wheel/source comparison; never import or extract wheel contents."""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path, PurePosixPath
from zipfile import BadZipFile, ZipFile

# Keep aligned with [tool.setuptools.package-data] in pyproject.toml.
RESOURCE_GLOBS = (
    "query/templates/*.yaml",
    "query/templates/*/*.yaml",
    "bundled_skills/**/*",
    "snapshot/LICENSE",
    "snapshot/PROVENANCE.md",
)


def _is_resource(name: str) -> bool:
    return (
        (name.startswith("pt_snap_cli/query/templates/") and name.endswith(".yaml"))
        or name.startswith("pt_snap_cli/bundled_skills/")
        or name in {"pt_snap_cli/snapshot/LICENSE", "pt_snap_cli/snapshot/PROVENANCE.md"}
    )


def audit_wheel(wheel: Path, source: Path) -> list[str]:
    """Compare Python modules and contracted resources to the supplied src tree."""
    package = source / "pt_snap_cli"
    if not (package / "__init__.py").is_file():
        raise ValueError(f"Expected source package at {package}")
    modules = {path.relative_to(source).as_posix(): path for path in package.rglob("*.py")}
    resources = {
        path.relative_to(source).as_posix(): path
        for pattern in RESOURCE_GLOBS
        for path in package.glob(pattern)
        if path.is_file()
    }
    errors: list[str] = []
    with ZipFile(wheel) as archive:
        names = [info.filename for info in archive.infolist() if not info.is_dir()]
        for name, count in sorted(Counter(names).items()):
            if count > 1:
                errors.append(f"Duplicate wheel member: {name}")
        # Distribution metadata (including licenses) is generated by the backend,
        # not copied one-to-one from src. Other non-contract data may ship via SCM.
        actual_modules = {
            name
            for name in names
            if name.endswith(".py") and not PurePosixPath(name).parts[0].endswith(".dist-info")
        }
        actual_resources = {name for name in names if _is_resource(name)}
        for label, expected, actual in (
            ("Python module", modules, actual_modules),
            ("resource", resources, actual_resources),
        ):
            for name in sorted(actual - expected.keys()):
                errors.append(f"Unexpected {label}: {name}")
            for name in sorted(expected.keys() - actual):
                errors.append(f"Missing {label}: {name}")
            for name in sorted(expected.keys() & actual):
                if archive.read(name) != expected[name].read_bytes():
                    errors.append(f"Content mismatch for {label}: {name}")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--wheel", required=True, type=Path)
    parser.add_argument("--source", type=Path, default=Path(__file__).resolve().parents[2] / "src")
    args = parser.parse_args()
    try:
        errors = audit_wheel(args.wheel, args.source)
    except (OSError, ValueError, BadZipFile) as exc:
        errors = [str(exc)]
    if errors:
        print("Wheel audit failed:\n" + "\n".join(errors), file=sys.stderr)
        print(
            "Rebuild from a fresh checkout/worktree; inspect build/lib for stale files. "
            "No files were modified by this audit.",
            file=sys.stderr,
        )
        return 1
    print(f"Wheel audit passed: {args.wheel}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
